# Gestão de Estoque
# Este arquivo funciona em conjunto com a extensão Rest Client do VSCode
# Instala a extensão e abra este arquivo no editor, então para cada GET, POST, PUT ou DELETE 
# no arquivo você poderá clicar em "Send Request" para ver o resultado

# Variáveis (edite caso a url do servidor mude)
@host = localhost:3000

### Hello (apenas um teste)
GET http://{{host}}/hello


#################################
## USUÁRIOS
#################################

###
# Obter todos os usuários
GET http://{{host}}/usuarios

### Adicionar um usuário
POST http://{{host}}/usuario

### Editar um usuário
PUT http://{{host}}/usuario

### Remover um usuário
DELETE http://{{host}}/usuario


